#!/usr/bin/env bash
set -e

BASE="$1"

if [ "$BASE" = "old" ]; then
    export STACK_YAML=stack-ghcjs-old-base.yaml
    if [ ! -d "reflex-dom" ]; then
        git clone -b develop https://github.com/ryantrinkle/reflex-dom.git
    fi
    sed -i.bak -e "s/bifunctors == 4\.2\.\*/bifunctors >= 4\.2/g" reflex-dom/reflex-dom.cabal
else
    export STACK_YAML=stack-ghcjs-improved-base.yaml
fi


stack setup
stack build


open_exe=$(which open)
local_install_root=$(stack path --local-install-root)
if [ -x "$open_exe" ]; then
    $open_exe "$local_install_root/bin/reflex-todomvc.jsexe/index.html"
fi

